# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plaintext = QtWidgets.QLabel(self.centralwidget)
        self.plaintext.setGeometry(QtCore.QRect(60, 130, 71, 16))
        self.plaintext.setObjectName("plaintext")
        self.key = QtWidgets.QLabel(self.centralwidget)
        self.key.setGeometry(QtCore.QRect(80, 250, 60, 16))
        self.key.setObjectName("key")
        self.ciphertext = QtWidgets.QLabel(self.centralwidget)
        self.ciphertext.setGeometry(QtCore.QRect(60, 360, 81, 16))
        self.ciphertext.setObjectName("ciphertext")
        self.bt_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.bt_encrypt.setGeometry(QtCore.QRect(200, 460, 113, 32))
        self.bt_encrypt.setObjectName("bt_encrypt")
        self.bt_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.bt_decrypt.setGeometry(QtCore.QRect(450, 460, 113, 32))
        self.bt_decrypt.setObjectName("bt_decrypt")
        self.tieuDe = QtWidgets.QLabel(self.centralwidget)
        self.tieuDe.setGeometry(QtCore.QRect(170, 10, 461, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.tieuDe.setFont(font)
        self.tieuDe.setObjectName("tieuDe")
        self.txt_plaintext = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plaintext.setGeometry(QtCore.QRect(140, 120, 511, 71))
        self.txt_plaintext.setObjectName("txt_plaintext")
        self.txt_key = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_key.setGeometry(QtCore.QRect(140, 240, 511, 31))
        self.txt_key.setObjectName("txt_key")
        self.txt_ciphertext = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_ciphertext.setGeometry(QtCore.QRect(140, 350, 511, 61))
        self.txt_ciphertext.setObjectName("txt_ciphertext")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plaintext.setText(_translate("MainWindow", "Plain Text :"))
        self.key.setText(_translate("MainWindow", "Key :"))
        self.ciphertext.setText(_translate("MainWindow", "CipherText :"))
        self.bt_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.bt_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.tieuDe.setText(_translate("MainWindow", "CAESAR CIPHER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
